server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/items/**
          filters:
            - AuthenticationFilter

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/**




